import { betterAuth } from "better-auth";
import { drizzleAdapter } from "better-auth/adapters/drizzle";
import { nextCookies } from "better-auth/next-js";
import { headers } from "next/headers";
import { eq } from "drizzle-orm";
import { db } from "@/lib/db";
import { account, session, users, verification } from "@/lib/db/schema";

const baseURL = process.env.BETTER_AUTH_URL ?? "http://localhost:3000";

export const auth = betterAuth({
  baseURL,
  secret: process.env.BETTER_AUTH_SECRET,
  database: drizzleAdapter(db, {
    provider: "pg",
    schema: {
      users,
      session,
      account,
      verification,
    },
  }),
  // Reuse the existing `users` table. Keep the singular model names for the
  // other core tables so `session`, `account` and `verification` map 1:1.
  user: {
    modelName: "users",
    fields: {
      id: "id",
      name: "name",
      email: "email",
      emailVerified: "emailVerified",
      image: "image",
      createdAt: "createdAt",
      updatedAt: "updatedAt",
    },
    additionalFields: {
      username: {
        type: "string",
        required: true,
        input: false,
        defaultValue: "",
      },
      siteTheme: {
        type: "string",
        required: false,
        input: false,
        defaultValue: "paper",
      },
    },
  },
  session: {
    modelName: "session",
    fields: {
      id: "id",
      userId: "userId",
      token: "token",
      expiresAt: "expiresAt",
      ipAddress: "ipAddress",
      userAgent: "userAgent",
      createdAt: "createdAt",
      updatedAt: "updatedAt",
    },
  },
  account: {
    modelName: "account",
    fields: {
      id: "id",
      userId: "userId",
      accountId: "accountId",
      providerId: "providerId",
      accessToken: "accessToken",
      refreshToken: "refreshToken",
      accessTokenExpiresAt: "accessTokenExpiresAt",
      refreshTokenExpiresAt: "refreshTokenExpiresAt",
      scope: "scope",
      idToken: "idToken",
      password: "password",
      createdAt: "createdAt",
      updatedAt: "updatedAt",
    },
  },
  verification: {
    modelName: "verification",
    fields: {
      id: "id",
      identifier: "identifier",
      value: "value",
      expiresAt: "expiresAt",
      createdAt: "createdAt",
      updatedAt: "updatedAt",
    },
  },
  socialProviders: {
    google: {
      clientId: process.env.GOOGLE_CLIENT_ID!,
      clientSecret: process.env.GOOGLE_CLIENT_SECRET!,
    },
  },
  // User ids are auto-increment serials generated by Postgres; sessions,
  // accounts and verifications get random UUIDs.
  advanced: {
    database: {
      generateId: (data) => {
        const model = String(data.model).toLowerCase();
        if (model === "user" || model === "users") return false;
        return crypto.randomUUID();
      },
    },
  },
  trustedOrigins: [baseURL],
  databaseHooks: {
    user: {
      create: {
        before: async (user) => {
          const username = await uniqueUsername(deriveUsername(user.email));
          return { data: { ...user, username } };
        },
      },
    },
  },
  plugins: [nextCookies()],
});

function deriveUsername(email: string): string {
  const local = email.split("@")[0] || "user";
  const base =
    local
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 32) || "user";
  return base;
}

async function uniqueUsername(base: string): Promise<string> {
  let candidate = base;
  let suffix = 2;
  for (;;) {
    const clash = await db
      .select({ id: users.username })
      .from(users)
      .where(eq(users.username, candidate))
      .limit(1);
    if (!clash[0]) return candidate;
    candidate = `${base}-${suffix++}`;
  }
}

export interface SessionUser {
  id: number;
  username: string;
  name: string;
  email: string;
  image: string;
}

export async function getSessionUser(): Promise<SessionUser | null> {
  const session = await auth.api.getSession({ headers: await headers() });
  if (!session) return null;
  const user = session.user;
  return {
    id: Number(user.id),
    username: user.username,
    name: user.name,
    email: user.email,
    image: user.image ?? "",
  };
}
